### PR TITLE
Changes with typing errors in Model1.html and header, h4,answer in Mo…

### PR DESCRIPTION
**Pull request by sanghisha145**
I did some changes around image in header, fixed some spelling mistakes in Model1.html and did some restructuring around h4, answer class.

### CODE REVIEW

**Comment by sanghisha145** [comment]
What is error in this?

**Comment by apuayush** [comment]
sorry had a merge conflict because of someone else's PR

**Comment by sanghisha145** [comment]
So are you able to merge pull request or I have to do some changes?

**Comment by apuayush** [comment]
No, i have resolved it.

**Pull request merged**
